spring:
  config:
    activate:
      on-profile: demo

tarbank:
  failure-simulator:
    enabled: ${TARBANK_FAILURE_SIMULATOR_ENABLED:true}
    failure-rate: ${TARBANK_FAILURE_SIMULATOR_FAILURE_RATE:0.15}
